name = "PiecewiseSplicedArrays"
uuid = "03528e14-9712-11e9-0cf3-01904f033ff3"
authors = ["Jishnu Bhattacharya <jishnuonline@gmail.com>"]
version = "0.1.0"

[deps]
PiecewiseIncreasingRanges = "efdf428f-f294-58b6-a961-90c8051bff4c"

[compat]
julia = "â‰¥ 1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
PiecewiseIncreasingRanges = "efdf428f-f294-58b6-a961-90c8051bff4c"

[targets]
test = ["Test","PiecewiseIncreasingRanges"]